routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Post;

Route::get('/', function () {
  $data=Post::all();
    return view('home',['data'=>$data]);
    // return view('home');
});

Route::get('about_us', function()
{
  $d="message";
    return view('aboutus')->with('test',$d);
})->name('about_us');

Route::get('write', function()
{
    return view('write');
})->middleware('auth');

// Route::get('/read/{post?}', function($postId='null')
// {
//     // return 'Reading post number '.$postId;
//     return view('read',['postId'=>$postId]);
// })->where(['post'=>'[0-9]{0,}'],[])->name('read');

// Route::get('login', function()
// {
//     return view('login');
// })->name("user_login");

Route::resource('post', 'PostController',['names'=>[
  'show'=>'read'
  ]]);


// Route::match(['get','patch'],'test', function()
// {
//     return 'TEST';
// });

// Route::any('/admin', function()
// {
//     return abort(404, 'Page not found');
// });

//this is a route to logout method in the login controller
//you shouldn't use the get method because it will logout other application
//other hack its stupid hidden form in ur logiut page with csrf field
Route::get('/logout', 'Auth\LoginController@logout');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Auth_controller.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Controllers\Controller;

class Auth_controller extends Controller
{
    /**
     * Show the profile for the given user.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        return view('user.profile', ['user' => User::findOrFail($id)]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data=Post::orderBy('created_at','DESC')->get();
          return view('home',['data'=>$data]);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // return view('home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);

        $this->validate($request, [
        'title' => 'required|unique:posts,title|max:80|min:5',
        'editor1' => 'required|max:8000|min:100',
        ],[
        'title.required' => 'This field is required. Please include title.',
        'editor1.required' => 'This field is required. Please write a Post.',
        ]);

       $post = new Post;
       $post->email = "dummy";
       $post->title = $request->title;
       $post->post = $request->editor1;

       $post->save();

       return redirect(url("/"));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $data = Post::findOrFail($id);
        //or use try and catch method with findOrFail and place the redirect to catch part

        $data = Post::find($id);
        if(is_null($data))
            {
                return redirect()->to("/");
        }
        else {
            return view('read',['data'=>$data]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::destroy($id);
        redirect('/');
    }
}

resources/views/home.blade.php
<!-- Stored in resources/views/child.blade.php -->

@extends('layouts.master')

@section('title', 'Blog Home')

@section('nav')
    @parent

    {{-- <p>Home nav.</p> --}}
@endsection

@section('side')
    @parent

    {{-- <p>Home nav.</p> --}}
@endsection


@section('content')
    <div class="container">
        <div class="blog-header">
        <h1 class="blog-title">The Teachy Blog</h1>
        <p class="lead blog-description">Junk MTV quiz graced by fox whelps.</p>
        </div>
    </div>

    @each('preview', $data, 'post')


              {{-- <nav>
                <ul class="pager">
                  <li><a href="#">Previous</a></li>
                  <li><a href="#">Next</a></li>
                </ul>
              </nav> --}}

            </div><!-- /.blog-main -->
            {{-- @foreach($data as $post)


            @endforeach --}}


@endsection




@section('footer')
    {{-- <p>Im the footer man i was yielded from the master blade.</p> --}}

@endsection

resources/views/include/footer.blade.php
<footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

resources/views/include/nav.blade.php
<div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item @if(Request::segment(1)=="")active @endif" href="{{url("/")}}">Home</a>
          <a class="blog-nav-item @if(Request::segment(1)=="write")active @endif" href="{{url("write")}}">Write Blog</a>
          <a class="blog-nav-item @if(Request::segment(1)=="post_action")active @endif" href="{{route("read",1)}}">Read</a>
          <a class="blog-nav-item @if(Request::segment(1)=="about_us")active @endif" href="{{route("about_us")}}">About</a>
          <div class="blog-nav navbar-right">
          <a class="blog-nav-item" style="color:white;">
          <?php
          use Illuminate\Support\Facades\Auth;
          $user=Auth::user();
          if($user!=""){
          echo "Welcome back ".$user['name'];
          }
          ?>
          </a>

          <?php
          $con=Auth::check();
          if($con){
          echo '<a class="blog-nav-item" href="'. route("logout").'">Logout</a>';
          }
          else{
          echo '<a class="blog-nav-item" href="'. route("login").'">Login</a>';
          }

          ?>
          </div>
        </nav>
      </div>
    </div>

resources/views/include/sidebar.blade.php
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Login-Teachy Blog</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        Teachy Blog
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/master.blade.php
<!-- Stored in resources/views/layouts/app.blade.php -->

<html>

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <title>@yield('title')</title>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- Custom styles for this template -->
  <link href="{{asset('css/blog.css')}}" rel="stylesheet">
</head>

<body>
  @section('nav')
    @include('include.nav')
  @show {{--
  <div class=""> --}}
   @yield('content') {{--
    <div class=""> --}}
    @include('include.sidebar')
    </div>
  </div>
  {{-- </div> --}}


  <div class="">
    @include('include.footer')
  </div>
</body>

</html>

resources/views/layouts/nonuser.blade.php
<!-- Stored in resources/views/layouts/app.blade.php -->

<html>

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <title>@yield('title')</title>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- Custom styles for this template -->
  <link href="{{asset('css/blog.css')}}" rel="stylesheet">
</head>

<body>
  @yield('content')

</body>

</html>

resources/views/login.blade.php
@extends('layouts.nonuser')


@section('content')

<style>
    body{
        background: #1e3c72;  /* fallback for old browsers */
        background: -webkit-linear-gradient(to right, #2a5298, #1e3c72);  /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to right, #2a5298, #1e3c72); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    }
    .vertical-offset-100{
        padding-top:100px;
    }
</style>

<script>
    // $(document).ready(function () {
    //     var error = "< $this->session->flashdata('msg') ?>";
    //     if (error != "") {
    //         $("#a1").show();
    //         function toggleDiv() {
    //             setTimeout(function () {
    //                 $("#a1").fadeOut("slow");
    //             }, 5000);
    //         }
    //         toggleDiv();
    //     }
    // }
    // );
</script>
<div style="position: absolute; display: none;" class="alert alert-danger text-center col-md-12" id="a1">
    < echo $this->session->flashdata('msg'); ?>
</div>

<div class="container">
    <div class="row vertical-offset-100">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please sign in</h3>
                </div>
                <div class="panel-body">
                    <form name="usercred" accept-charset="UTF-8" method="post" action="" role="form">
                        <fieldset>
                            <div class="form-group">
                                <label class="label">Username</label>
                                <input class="form-control" placeholder="Username" name="username" type="text">
                            </div>
                            <div class="form-group">
                                <label class="label ">Password</label>
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember me"> Remember me.
                                </label>
                            </div>
                            <input class="btn btn-lg btn-primary btn-block" type="submit" value="Login">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/preview.blade.php
<div class="container">


        <div class="row">

          <div class="col-sm-8 blog-main">

            <div class="blog-post">
              <h2 class="blog-post-title">{{ $post->title }}</h2>
              <p class="blog-post-meta">{{ $post->created_at }} by <a href="#">{{ $post->email }}</a></p>
                  @php
                  $string = $post->post;
                  $string = strip_tags($string);
                  if (strlen($string) > 500) {
                      $stringCut = substr($string, 0, 500);
                      $num=$post->id;
                      $string = substr($stringCut, 0, strrpos($stringCut, ' ')) . '... <a href='. route("read",$num).'>Read More</a>';
                  }
                  echo $string;
                  @endphp

            </div><!-- /.blog-post -->

resources/views/read.blade.php
@extends('layouts.master')

@section('title','Post')

@section('nav')
    @parent

    {{-- <p>Home nav.</p> --}}
@endsection

@section('content')

<div class="container">
{{-- {{$post->all()}} --}}
      <div class="blog-header">
        <h1 class="blog-title">The Teachy Blog</h1>
        <p class="lead blog-description">Junk MTV quiz graced by fox whelps.</p>
      </div>
      {{-- {{print_r($data)}} --}}
      <div class="row">
          
        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">{{$data->title}}</h2>
            <p class="blog-post-meta">{{$data->created_at." by"}} <a href="#">{{$data->email}}</a></p>
            <p> {!!$data->post!!} </p>
        </div>
        <nav>
          <ul class="pager">
            <li>
                <form class="" action="{{route("post.destroy",$data->id)}}" method="post">
                                {{ method_field('DELETE') }}
                                {{CSRF_field()}}
                <input type="hidden" name="id" value="{{$data->id}}">
                <button class="btn btn-danger">Delete Post</button>
            </form>
            </li>
            <li><a href="{{route("read",$data->id-1)}}">Previous</a></li>
            <li><a href="{{route("read",$data->id+1)}}">Next</a></li>
          </ul>
        </nav>
    </div>
{{-- </div> --}}
{{-- </div> --}}

@endsection

@section('sidebar')
    {{-- <p>This is my sidebar.</p> --}}

@endsection

@section('footer')

@endsection

resources/views/write.blade.php
@extends('layouts.master')

@section('title','Post')

@section('nav')
    @parent

    {{-- <p>Home nav.</p> --}}
@endsection

@section('content')
<script src="//cdn.ckeditor.com/4.6.2/basic/ckeditor.js"></script>

<div id='a1' style="position: absolute; display: none;" class="alert alert-danger text-center col-md-12">
    @if (count($errors) > 0)
        <div class="container">

                @foreach ($errors->all() as $error)
                    {{ $error }}<br>
                @endforeach

        </div>
    @endif
</div>

<div class="container">

    <div class="blog-header">
      <h1 class="blog-title">The Teachy Blog</h1>
      <p class="lead blog-description">Junk MTV quiz graced by fox whelps.</p>
    </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">

            <h2 class="blog-post-title">Write a post:</h2>
    <div class="row">
        <div class="col-md-6 col-md-offest-4">
                <form method="post" action="{{route("post.store")}}" name="userpost">
                    {{CSRF_field()}}
                    <div  style="display: none" id="text-editor" class="row">
                        <div class="form-group row col-md-8 col-md-offset-2">
                            <label class=" control-label" for="title">Title:</label>
                            <input  name="title" type="text" placeholder="" class="form-control input-md">
                        </div>
                        <div class="form-group">
                            <div class="container col-md-8 col-md-offset-2">
                                <label class=" control-label">Post:</label>
                                <textarea class="hidden" name="editor1"></textarea>
                                <br>
                                <button id="btn1" class="btn btn-primary">Publish Post</button>
                                <a href="{{url("/")}}"><input type="button" value="Cancel" id="btn2" class="btn btn-default"></a>
                            </div>
                        </div>
                    </div>
                </form>
         </div>
     </div>
        </div>
    </div>

<script>
    $(document).ready(function () {
        CKEDITOR.replace('editor1', {
          width:['60%'],uiColor: '#428bca',

            on: {
                instanceReady: function (evt) {
                    $("#text-editor").fadeIn("slow");
                }
            }
        });

        var error ={{count($errors)}};
        if (parseInt(error) > 0) {
            $("#a1").show();
            function toggleDiv() {
                setTimeout(function () {
                    $("#a1").fadeOut("slow");
                }, 5000);
            }
            toggleDiv();
        }
    }
    );

</script>
@endsection

@section('sidebar')
    {{-- <p>This is my sidebar.</p> --}}

@endsection

@section('footer')

@endsection